### ISSUE TITLE
Using indian numbers instead of arabic when language is set to arabic

### ISSUE THREAD

**Issue by nacer-benyoub** [abdallahmehiz/progres#1]
I would suggest using arabic numbers (1, 2, 3) instead of indian numbers (١، ٢، ٣) when the app language is set to arabic as they are clearer and the users are more familiar with them.

**Comment by abdallahmehiz** [comment]
Depends on locale, if you use the system language in the app's settings and select arabic (algeria) in the app's system settings it'll use algerian locale which uses arabic numbers. I will fix make it uses the exact locale in a fix soon, thanks for the feedback.
